export const ACTION_TYPES = {
    SET_TIMEOUT: 'SET_TIMEOUT',
    ADD_ITEM_TO_QUEUE: 'ADD_ITEM_TO_QUEUE',
    REMOVE_FROM_QUEUE: 'REMOVE_FROM_QUEUE',
    LOG_ERROR: 'LOG_ERROR',
    ON_COMPLETE: 'ON_COMPLETE',
    ON_FAILED: 'ON_FAILED'
};